Задание №2: Предложите исправление представленого ниже кода
```C
FILE *f = fopen(name, “w”);
// Тут код, при котором может быть выброшено исключение
fclose(f);
```
Ответ: Приведенный выше код в случае генерации исключения не выполняет корректного закрытия файла f.
Предлагаемое исправление: добавление обработки исключений и замена fopen() и fclose() на std::ofstream.
```C
#include <fstream>
...
try 
{
	std::ofstream f(name);
	// Тут код, при котором может быть выброшено исключение
}
catch(...) 
{
	std::cerr << "Unexpected exception!";
}

```
В случае генерации исключения, обработчик исключения вызовет деструктор для std::ofstream f.